openapi: 3.1.0
info:
  title: Lending Service
  version: '1.0'
  summary: API for lending medias
  description: This API allows to lend and return medias
  contact:
    name: Christian Langmann
    email: c_langmann@gmx.de
servers:
  - url: 'http://localhost:8080/lending'
    description: lending
paths:
  /lendings:
    parameters: []
    get:
      summary: Get lendings
      operationId: get-lendings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Lending'
      description: |-
        Get all lendings

        TODO: 
        - Must be paged
        - Must be filtered
      parameters:
        - schema:
            type: string
          in: query
          name: userId
          description: id of the user whose lendings should be listed
      tags:
        - lending
        - list
    post:
      summary: Start a lending
      operationId: post-lendings
      responses:
        '201':
          description: Created lending
      description: start lending some items
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: ../model/Uuid.yaml
      tags:
        - lending
        - item
  '/lendings/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: The id of a lending
    get:
      summary: Get a lending
      description: 'Get a specfic landing, identified by parameter id'
      tags: []
      responses:
        '200':
          description: Return a detailed lending if the requested one exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lending'
        '404':
          description: A lending with this id was not found
      operationId: get-lendings-id
components:
  schemas:
    Item:
      title: Item
      type: object
      description: An item that can be lend
      properties:
        itemId:
          $ref: ../model/Uuid.yaml
        type:
          $ref: ../model/ItemType.yaml
        name:
          type: string
        externalId:
          type: string
          description: 'An external ID identifes an item by an id that is globally defined within a catalog by an external authority. E.g. Books have an ISBN. '
      required:
        - itemId
        - type
        - name
        - externalId
    Lending:
      title: Lending
      description: 'Describing the lending process, containing the customer, the items lend and the conditions, like date.'
      type: object
      properties:
        lendingId:
          $ref: ../model/Uuid.yaml
        startDate:
          description: Start of lending
          type: datetime
        items:
          type: array
          items:
            $ref: '#/components/schemas/LentItem'
        customerId:
          $ref: ../model/Uuid.yaml
      required:
        - lendingId
    LentItem:
      title: LentItem
      type: object
      properties:
        itemId:
          $ref: ../model/Uuid.yaml
        endOfLend:
          type: string
          format: datetime
          example: '2014-01-01T0:00:00Z'
        item:
          $ref: '#/components/schemas/Item'
      required:
        - itemId
        - endOfLend
tags:
  - name: lending
  - name: list
  - name: item
